apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: request-approval
  title: Request Approval
  description: Submit a request for manager approval.
spec:
  owner: user:default/chitta
  type: service
  parameters:
    - title: Request Details
      required:
        - requestor
        - requestType
      properties:
        requestor:
          title: "Requester Name"
          type: string
          description: "Enter your name"
        requestType:
          title: "Request Type"
          type: string
          enum:
            - "VM Access Request"
            - "Other"
          description: "Select the type of request"
        description:
          type: string
          title: Request Description
    - title: "Approval"
      required:
        - approver
      properties:
        approver:
          title: "Approver Email"
          type: string
          description: "Enter the email of the approver"
  steps:
    - id: approval-step
      name: Request Approval
      action: custom.helloWorld
      input:
        owner: chitta-behera
        repo: s3-workflow
        title: Approval needed for ${{ parameters.requestor }}
        onApprove:
          - action: debug:log
            input:
              message: "🚀 Approval received! Proceeding with execution."
  output:
    helloMessage: "Hello, ${{ parameters.requestor }}!"
