apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: request-approval
  title: Request Approval
  description: Submit a request for manager approval.
spec:
  owner: user:default/chitta
  type: service
  parameters:
    - title: Request Details
      required:
        - requestor
        - requestType
      properties:
        requestor:
          title: "Requester Name"
          type: string
          description: "Enter your name"
        requestType:
          title: "Request Type"
          type: string
          enum:
            - "VM Access Request"
            - "Other"
          description: "Select the type of request"
        description:
          type: string
          title: Request Description
    - title: "Approval"
      required:
        - approver
      properties:
        approver:
          title: "Approver Email"
          type: string
          description: "Enter the email of the approver"
  steps:
    - id: submit-request
      name: Submit Request
      action: roadiehq:utils:wait
      input:
        seconds: 5
      output:
        message: "Request submitted successfully!"

    - id: wait-for-approval
      name: "Waiting for Approval"
      action: roadiehq:utils:manual-approval
      input:
        description: "Approve or reject the request"
        approvers:
          - "${{ parameters.approver }}"
      output:
        approved: true

    - id: process-request
      name: Process the Request
      if: "${{ steps.wait-for-approval.output.approved }}"
      action: roadiehq:utils:wait
      input:
        seconds: 5
      output:
        message: "Request approved! Proceeding with next steps."

    - id: reject-request
      name: Request Rejected
      if: "${{ not steps.wait-for-approval.output.approved }}"
      action: roadiehq:utils:fail
      input:
        message: "Request rejected. No further action taken."

  output:
    message: "Request completed successfully!"
