apiVersion: marketplace.kratix.io/v1alpha2
kind: postgresql
metadata:
  name: example
  namespace: default
spec:
  env: dev
  teamId: acme-org-team-a
  dbName: bestdb-backstage
  backupEnabled: false
